spring:
  data:
    mongodb:
      uri: mongodb://mongo_admin:mongo_admin@localhost:27017/customer?authSource=admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orderGroup,paymentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ecommarce.kafka.order.OrderConfirmation,paymentConfirmation:com.ecommarce.kafka.payment.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          trust: '*'
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8090
