spring:
  application:
    config:
      customer-url: http://localhost:8222/api/v1/customers
      product-url: http://localhost:8222/api/v1/payments
      payment-url: http://localhost:8222/api/v1/products

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.ecommarce.order.dto.OrderConfirmation
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8070
#    customer-url: http://locahlhost:8090/api/v1/customers
#    product-url: http://locahlhost:8060/api/v1/payments
#    payment-url: http://locahlhost:8050/api/v1/products
#   application.config.payment-url